server {
  listen 8080;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = /env.js {
    default_type application/javascript;
    add_header Cache-Control "no-store";
    alias /tmp/env.js;
  }

  location / {
    try_files $uri /index.html;
  }
}
